pool:
  name: MyAgent  # This specifies the self-hosted agent pool you've created

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Static Web Apps require Node.js for build, even for HTML projects
  
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/build'  # Change this to the directory containing your index.html if not in root
    output_location: '/'  # Change if you want to specify a different directory for output
    azure_static_web_apps_api_token: $(deployment_token)
  env:
    deployment_token: $(deployment_token)  # Set in pipeline variables
